apiVersion: azuread.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: azuread-creds
spec:
  credentials:
    source: Secret
    secretRef:
      name: azuread-creds
      namespace: crossplane-system
      key: credentials
