apiVersion: application.azuread.jet.crossplane.io/v1alpha1
kind: Application
metadata:
  name: azuread-application
spec:
  forProvider:
    displayName: azuread-application
  providerConfigRef:
    name: azuread-creds
