apiVersion: application.azuread.jet.crossplane.io/v1alpha1
kind: Application
metadata:
  name: azuread-application
spec:
  forProvider:
    displayName: azuread-application
    owners: [ "000000-0000-0000-0000-000000000000" ]
    requiredResourceAccess: 
    - resourceAppId: "000000-0000-0000-0000-000000000000"
      resourceAccess:
      - id: "000000-0000-0000-0000-000000000000"
        type: "Scope"
  providerConfigRef:
    name: azuread-creds
