apiVersion: azuread.azuread.jet.crossplane.io/v1alpha1
kind: Application
metadata:
  name: azuread-application
  annotations:
    crossplane.io/external-name: my-special-db
spec:
  forProvider:
    displayName: test_application
    lifecycle:
      name: test
  providerConfigRef:
    name: azuread-creds
